INSERT INTO cafecoder.contests(id, name, start_time, end_time) VALUES('tea003', 'tea003', '2019-12-22 18:00:00','2019-12-22 19:30:00');
INSERT INTO cafecoder.problems(id, contest_id, name, point, testcase_id) VALUES('tea003A','tea003', 'A', 50, 'tea003A');
INSERT INTO cafecoder.testcases(id, problem_id, listpath)VALUES('tea003A','tea003A', '/home/cafecoder-judge/testcase/tea003/A/');
INSERT INTO cafecoder.problems(id, contest_id, name, point, testcase_id) VALUES('tea003B','tea003', 'B', 100, 'tea003B');
INSERT INTO cafecoder.testcases(id, problem_id, listpath)VALUES('tea003B','tea003B', '/home/cafecoder-judge/testcase/tea003/B/');
INSERT INTO cafecoder.problems(id, contest_id, name, point, testcase_id) VALUES('tea003C','tea003', 'C', 150, 'tea003C');
INSERT INTO cafecoder.testcases(id, problem_id, listpath)VALUES('tea003C','tea003C', '/home/cafecoder-judge/testcase/tea003/C/');
INSERT INTO cafecoder.problems(id, contest_id, name, point, testcase_id) VALUES('tea003D','tea003', 'D', 200, 'tea003D');
INSERT INTO cafecoder.testcases(id, problem_id, listpath)VALUES('tea003D','tea003D', '/home/cafecoder-judge/testcase/tea003/D/');
INSERT INTO cafecoder.problems(id, contest_id, name, point, testcase_id) VALUES('tea003E','tea003', 'E', 250, 'tea003E');
INSERT INTO cafecoder.testcases(id, problem_id, listpath)VALUES('tea003E','tea003E', '/home/cafecoder-judge/testcase/tea003/E/');
INSERT INTO cafecoder.problems(id, contest_id, name, point, testcase_id) VALUES('tea003F','tea003', 'F', 300, 'tea003F');
INSERT INTO cafecoder.testcases(id, problem_id, listpath)VALUES('tea003F','tea003F', '/home/cafecoder-judge/testcase/tea003/F/');
